import 'package:blockchain_utils/blockchain_utils.dart';
import 'package:cosmos_sdk/proto_messages/types.dart';
import 'package:cosmos_sdk/sdk/serialization/serialization.dart';
import "package:cosmos_sdk/proto_messages/google/protobuf/src/timestamp.dart"
    as google_protobuf_timestamp;
import "package:cosmos_sdk/proto_messages/google/protobuf/src/duration.dart"
    as google_protobuf_duration;
import "package:cosmos_sdk/proto_messages/cosmos/base/v1beta1/src/coin.dart"
    as cosmos_base_v1beta1_coin;

/// this is a legacy package that requires additional migration logic
/// in order to use the correct package. Decision made to use legacy package path
/// until clear steps for migration logic and the unknowns for state breaking are
/// investigated for changing proto package.
/// Parameters for changing the weights in a balancer pool smoothly from
/// a start weight and end weight over a period of time.
/// Currently, the only smooth change supported is linear changing between
/// the two weights, but more types may be added in the future.
/// When these parameters are set, the weight w(t) for pool time `t` is the
/// following:
/// t <= start_time: w(t) = initial_pool_weights
/// start_time < t <= start_time + duration:
/// w(t) = initial_pool_weights + (t - start_time) *
/// (target_pool_weights - initial_pool_weights) / (duration)
/// t > start_time + duration: w(t) = target_pool_weights
class SmoothWeightChangeParams extends CosmosProtoMessage {
  /// The start time for beginning the weight change.
  /// If a parameter change / pool instantiation leaves this blank,
  /// it should be generated by the state_machine as the current time.
  final google_protobuf_timestamp.Timestamp? startTime;

  /// Duration for the weights to change over
  final google_protobuf_duration.Duration? duration;

  /// The initial pool weights. These are copied from the pool's settings
  /// at the time of weight change instantiation.
  /// The amount PoolAsset.token.amount field is ignored if present,
  /// future type refactorings should just have a type with the denom & weight
  /// here.
  final List<PoolAsset> initialPoolWeights;

  /// The target pool weights. The pool weights will change linearly with respect
  /// to time between start_time, and start_time + duration. The amount
  /// PoolAsset.token.amount field is ignored if present, future type
  /// refactorings should just have a type with the denom & weight here.
  final List<PoolAsset> targetPoolWeights;

  const SmoothWeightChangeParams({
    this.startTime,
    this.duration,
    this.initialPoolWeights = const [],
    this.targetPoolWeights = const [],
  });

  @override
  ProtoMessageConfig protoConfig() => protoConfigStatic();

  static ProtoMessageConfig protoConfigStatic() {
    return ProtoMessageConfig(
      syntax: ProtoSyntax.v3,
      options: const [],
      fields: [
        ProtoFieldConfig.message(1, options: const []),
        ProtoFieldConfig.message(2, options: const []),
        ProtoFieldConfig.repeated(
          fieldNumber: 3,
          elementType: ProtoFieldType.message,
          options: const [],
        ),
        ProtoFieldConfig.repeated(
          fieldNumber: 4,
          elementType: ProtoFieldType.message,
          options: const [],
        ),
      ],
    );
  }

  @override
  List<Object?> get protoValues => [
    startTime,
    duration,
    initialPoolWeights,
    targetPoolWeights,
  ];

  @override
  Map<String, dynamic> toJson() {
    return {
      'start_time': startTime?.toRfc3339(),
      'duration': duration?.encodeString(asNanos: true),
      'initial_pool_weights':
          initialPoolWeights.map((e) => e.toJson()).toList(),
      'target_pool_weights': targetPoolWeights.map((e) => e.toJson()).toList(),
    };
  }

  factory SmoothWeightChangeParams.fromJson(Map<String, dynamic> json) {
    return SmoothWeightChangeParams(
      startTime: json.valueTo<google_protobuf_timestamp.Timestamp?, String>(
        key: 'start_time',
        parse: (v) => google_protobuf_timestamp.Timestamp.fromRfc3339(v),
        acceptCamelCase: true,
      ),
      duration: json.valueTo<google_protobuf_duration.Duration?, String>(
        key: 'duration',
        parse: (v) => google_protobuf_duration.Duration.fromString(v),
        acceptCamelCase: true,
      ),
      initialPoolWeights:
          (json.valueEnsureAsList<dynamic>(
                'initial_pool_weights',
                acceptCamelCase: true,
              ))
              .map(
                (e) => JsonParser.valueTo<PoolAsset, Map<String, dynamic>>(
                  value: e,
                  parse: (v) => PoolAsset.fromJson(v),
                ),
              )
              .toList(),
      targetPoolWeights:
          (json.valueEnsureAsList<dynamic>(
                'target_pool_weights',
                acceptCamelCase: true,
              ))
              .map(
                (e) => JsonParser.valueTo<PoolAsset, Map<String, dynamic>>(
                  value: e,
                  parse: (v) => PoolAsset.fromJson(v),
                ),
              )
              .toList(),
    );
  }

  factory SmoothWeightChangeParams.deserialize(List<int> bytes) {
    final decode = CosmosProtoMessage.decode(bytes, protoConfigStatic());
    return SmoothWeightChangeParams(
      startTime: decode.messageTo<google_protobuf_timestamp.Timestamp?>(
        1,
        (b) => google_protobuf_timestamp.Timestamp.deserialize(b),
      ),
      duration: decode.messageTo<google_protobuf_duration.Duration?>(
        2,
        (b) => google_protobuf_duration.Duration.deserialize(b),
      ),
      initialPoolWeights:
          decode
              .getListOfBytes(3)
              .map((b) => PoolAsset.deserialize(b))
              .toList(),
      targetPoolWeights:
          decode
              .getListOfBytes(4)
              .map((b) => PoolAsset.deserialize(b))
              .toList(),
    );
  }

  @override
  DefaultCosmosProtoTypeUrl get declarationId =>
      DefaultCosmosProtoTypeUrl.osmosisGammV1beta1SmoothWeightChangeParams;
}

/// Intermediate variable for the 'slope' of pool weights. This is equal to
/// (target_pool_weights - initial_pool_weights) / (duration)
/// repeated PoolAsset poolWeightSlope = 5 [
/// (gogoproto.moretags) = "yaml:\"pool_weight_slope\"",
/// (gogoproto.nullable) = false
/// ];
/// PoolParams defined the parameters that will be managed by the pool
/// governance in the future. This params are not managed by the chain
/// governance. Instead they will be managed by the token holders of the pool.
/// The pool's token holders are specified in future_pool_governor.
class PoolParams extends CosmosProtoMessage {
  final String? swapFee;

  /// N.B.: exit fee is disabled during pool creation in x/poolmanager. While old
  /// pools can maintain a non-zero fee. No new pool can be created with non-zero
  /// fee anymore
  final String? exitFee;

  final SmoothWeightChangeParams? smoothWeightChangeParams;

  const PoolParams({this.swapFee, this.exitFee, this.smoothWeightChangeParams});

  @override
  ProtoMessageConfig protoConfig() => protoConfigStatic();

  static ProtoMessageConfig protoConfigStatic() {
    return ProtoMessageConfig(
      syntax: ProtoSyntax.v3,
      options: [
        ProtoOptionString(
          name: "amino.name",
          value: "osmosis/gamm/BalancerPoolParams",
        ),
      ],
      fields: [
        ProtoFieldConfig.string(1, options: const []),
        ProtoFieldConfig.string(2, options: const []),
        ProtoFieldConfig.message(3, options: const []),
      ],
    );
  }

  @override
  List<Object?> get protoValues => [swapFee, exitFee, smoothWeightChangeParams];

  @override
  Map<String, dynamic> toJson() {
    return {
      'swap_fee': swapFee,
      'exit_fee': exitFee,
      'smooth_weight_change_params': smoothWeightChangeParams?.toJson(),
    };
  }

  factory PoolParams.fromJson(Map<String, dynamic> json) {
    return PoolParams(
      swapFee: json.valueAsString<String?>('swap_fee', acceptCamelCase: true),
      exitFee: json.valueAsString<String?>('exit_fee', acceptCamelCase: true),
      smoothWeightChangeParams: json
          .valueTo<SmoothWeightChangeParams?, Map<String, dynamic>>(
            key: 'smooth_weight_change_params',
            parse: (v) => SmoothWeightChangeParams.fromJson(v),
            acceptCamelCase: true,
          ),
    );
  }

  factory PoolParams.deserialize(List<int> bytes) {
    final decode = CosmosProtoMessage.decode(bytes, protoConfigStatic());
    return PoolParams(
      swapFee: decode.getString<String?>(1),
      exitFee: decode.getString<String?>(2),
      smoothWeightChangeParams: decode.messageTo<SmoothWeightChangeParams?>(
        3,
        (b) => SmoothWeightChangeParams.deserialize(b),
      ),
    );
  }

  @override
  DefaultCosmosProtoTypeUrl get declarationId =>
      DefaultCosmosProtoTypeUrl.osmosisGammV1beta1PoolParams;
}

/// Pool asset is an internal struct that combines the amount of the
/// token in the pool, and its balancer weight.
/// This is an awkward packaging of data,
/// and should be revisited in a future state migration.
class PoolAsset extends CosmosProtoMessage {
  /// Coins we are talking about,
  /// the denomination must be unique amongst all PoolAssets for this pool.
  final cosmos_base_v1beta1_coin.Coin? token;

  /// Weight that is not normalized. This weight must be less than 2^50
  final String? weight;

  const PoolAsset({this.token, this.weight});

  @override
  ProtoMessageConfig protoConfig() => protoConfigStatic();

  static ProtoMessageConfig protoConfigStatic() {
    return ProtoMessageConfig(
      syntax: ProtoSyntax.v3,
      options: const [],
      fields: [
        ProtoFieldConfig.message(1, options: const []),
        ProtoFieldConfig.string(2, options: const []),
      ],
    );
  }

  @override
  List<Object?> get protoValues => [token, weight];

  @override
  Map<String, dynamic> toJson() {
    return {'token': token?.toJson(), 'weight': weight};
  }

  factory PoolAsset.fromJson(Map<String, dynamic> json) {
    return PoolAsset(
      token: json.valueTo<cosmos_base_v1beta1_coin.Coin?, Map<String, dynamic>>(
        key: 'token',
        parse: (v) => cosmos_base_v1beta1_coin.Coin.fromJson(v),
        acceptCamelCase: true,
      ),
      weight: json.valueAsString<String?>('weight', acceptCamelCase: true),
    );
  }

  factory PoolAsset.deserialize(List<int> bytes) {
    final decode = CosmosProtoMessage.decode(bytes, protoConfigStatic());
    return PoolAsset(
      token: decode.messageTo<cosmos_base_v1beta1_coin.Coin?>(
        1,
        (b) => cosmos_base_v1beta1_coin.Coin.deserialize(b),
      ),
      weight: decode.getString<String?>(2),
    );
  }

  @override
  DefaultCosmosProtoTypeUrl get declarationId =>
      DefaultCosmosProtoTypeUrl.osmosisGammV1beta1PoolAsset;
}
