# include: package:lints/recommended.yaml
include: package:flutter_lints/flutter.yaml
# Uncomment the following section to specify additional rules.
linter:
  rules:
    prefer_final_locals: true        # Warns when a local variable could be final
    prefer_final_in_for_each: true   # Warns when a forEach variable could be final
    prefer_const_constructors: true  # Warns when a constructor could be const
    prefer_const_declarations: true  # Warns when a declaration could be const
