import 'package:blockchain_utils/blockchain_utils.dart';
import 'package:cosmos_sdk/proto_messages/types.dart';
import 'package:cosmos_sdk/sdk/serialization/serialization.dart';

/// Log represents an protobuf compatible Ethereum Log that defines a contract
/// log event. These events are generated by the LOG opcode and stored/indexed by
/// the node.
///
/// NOTE: address, topics and data are consensus fields. The rest of the fields
/// are derived, i.e. filled in by the nodes, but not secured by consensus.
class Log extends CosmosProtoMessage {
  /// address of the contract that generated the event
  final String? address;

  /// topics is a list of topics provided by the contract.
  final List<String> topics;

  /// data which is supplied by the contract, usually ABI-encoded
  final List<int>? data;

  /// block_number of the block in which the transaction was included
  final BigInt? blockNumber;

  /// tx_hash is the transaction hash
  final String? txHash;

  /// tx_index of the transaction in the block
  final BigInt? txIndex;

  /// block_hash of the block in which the transaction was included
  final String? blockHash;

  /// index of the log in the block
  final BigInt? index;

  /// removed is true if this log was reverted due to a chain
  /// reorganisation. You must pay attention to this field if you receive logs
  /// through a filter query.
  final bool? removed;

  const Log({
    this.address,
    this.topics = const [],
    this.data,
    this.blockNumber,
    this.txHash,
    this.txIndex,
    this.blockHash,
    this.index,
    this.removed,
  });

  @override
  ProtoMessageConfig protoConfig() => protoConfigStatic();

  static ProtoMessageConfig protoConfigStatic() {
    return ProtoMessageConfig(
      syntax: ProtoSyntax.v3,
      options: const [],
      fields: [
        ProtoFieldConfig.string(1),
        ProtoFieldConfig.repeated(
          fieldNumber: 2,
          elementType: ProtoFieldType.string,
        ),
        ProtoFieldConfig.bytes(3),
        ProtoFieldConfig.uint64(4, options: const []),
        ProtoFieldConfig.string(5, options: const []),
        ProtoFieldConfig.uint64(6, options: const []),
        ProtoFieldConfig.string(7, options: const []),
        ProtoFieldConfig.uint64(8, options: const []),
        ProtoFieldConfig.bool(9),
      ],
    );
  }

  @override
  List<Object?> get protoValues => [
    address,
    topics,
    data,
    blockNumber,
    txHash,
    txIndex,
    blockHash,
    index,
    removed,
  ];

  @override
  Map<String, dynamic> toJson() {
    return {
      'address': address,
      'topics': topics.map((e) => e).toList(),
      'data': switch (data) {
        List<int> bytes => StringUtils.decode(
          bytes,
          encoding: StringEncoding.base64,
        ),
        _ => null,
      },
      'block_number': blockNumber?.toString(),
      'tx_hash': txHash,
      'tx_index': txIndex?.toString(),
      'block_hash': blockHash,
      'index': index?.toString(),
      'removed': removed,
    };
  }

  factory Log.fromJson(Map<String, dynamic> json) {
    return Log(
      address: json.valueAsString<String?>('address', acceptCamelCase: true),
      topics:
          (json.valueEnsureAsList<dynamic>(
            'topics',
            acceptCamelCase: true,
          )).map((e) => JsonParser.valueAsString<String>(e)).toList(),
      data: json.valueAsBytes<List<int>?>(
        'data',
        acceptCamelCase: true,
        encoding: StringEncoding.base64,
      ),
      blockNumber: json.valueAsBigInt<BigInt?>(
        'block_number',
        acceptCamelCase: true,
      ),
      txHash: json.valueAsString<String?>('tx_hash', acceptCamelCase: true),
      txIndex: json.valueAsBigInt<BigInt?>('tx_index', acceptCamelCase: true),
      blockHash: json.valueAsString<String?>(
        'block_hash',
        acceptCamelCase: true,
      ),
      index: json.valueAsBigInt<BigInt?>('index', acceptCamelCase: true),
      removed: json.valueAsBool<bool?>('removed', acceptCamelCase: true),
    );
  }

  factory Log.deserialize(List<int> bytes) {
    final decode = CosmosProtoMessage.decode(bytes, protoConfigStatic());
    return Log(
      address: decode.getString<String?>(1),
      topics: decode.getListOrEmpty<String>(2),
      data: decode.getBytes<List<int>?>(3),
      blockNumber: decode.getBigInt<BigInt?>(4),
      txHash: decode.getString<String?>(5),
      txIndex: decode.getBigInt<BigInt?>(6),
      blockHash: decode.getString<String?>(7),
      index: decode.getBigInt<BigInt?>(8),
      removed: decode.getBool<bool?>(9),
    );
  }

  @override
  DefaultCosmosProtoTypeUrl get declarationId =>
      DefaultCosmosProtoTypeUrl.injectiveEvmV1Log;
}
